// Code generated by protoc-gen-go.
// source: data.proto
// DO NOT EDIT!

/*
Package lm is a generated protocol buffer package.

It is generated from these files:
	data.proto

It has these top-level messages:
	Data
*/
package lm

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Data_MessageType int32

const (
	Data_USER    Data_MessageType = 0
	Data_MESSAGE Data_MessageType = 1
	Data_RESULT  Data_MessageType = 2
)

var Data_MessageType_name = map[int32]string{
	0: "USER",
	1: "MESSAGE",
	2: "RESULT",
}
var Data_MessageType_value = map[string]int32{
	"USER":    0,
	"MESSAGE": 1,
	"RESULT":  2,
}

func (x Data_MessageType) Enum() *Data_MessageType {
	p := new(Data_MessageType)
	*p = x
	return p
}
func (x Data_MessageType) String() string {
	return proto.EnumName(Data_MessageType_name, int32(x))
}
func (x *Data_MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Data_MessageType_value, data, "Data_MessageType")
	if err != nil {
		return err
	}
	*x = Data_MessageType(value)
	return nil
}

type Data struct {
	Version          *int32        `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	Type             *int32        `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	Time             *uint64       `protobuf:"varint,3,req,name=time" json:"time,omitempty"`
	User             *Data_User    `protobuf:"bytes,7,opt,name=user" json:"user,omitempty"`
	Msg              *Data_Message `protobuf:"bytes,8,opt,name=msg" json:"msg,omitempty"`
	Res              *Data_Result  `protobuf:"bytes,9,opt,name=res" json:"res,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}

func (m *Data) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *Data) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Data) GetTime() uint64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Data) GetUser() *Data_User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Data) GetMsg() *Data_Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Data) GetRes() *Data_Result {
	if m != nil {
		return m.Res
	}
	return nil
}

type Data_Result struct {
	// ////告知发送方  是否接收到消息
	Msg              *string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	Code             *int32  `protobuf:"varint,2,req,name=code" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Data_Result) Reset()         { *m = Data_Result{} }
func (m *Data_Result) String() string { return proto.CompactTextString(m) }
func (*Data_Result) ProtoMessage()    {}

func (m *Data_Result) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *Data_Result) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

type Data_User struct {
	User             *string `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	Password         *string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Token            *string `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Data_User) Reset()         { *m = Data_User{} }
func (m *Data_User) String() string { return proto.CompactTextString(m) }
func (*Data_User) ProtoMessage()    {}

func (m *Data_User) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *Data_User) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *Data_User) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type Data_Message struct {
	Content          *string `protobuf:"bytes,1,req,name=content" json:"content,omitempty"`
	Accept           *string `protobuf:"bytes,2,opt,name=accept" json:"accept,omitempty"`
	Send             *string `protobuf:"bytes,3,opt,name=send" json:"send,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Data_Message) Reset()         { *m = Data_Message{} }
func (m *Data_Message) String() string { return proto.CompactTextString(m) }
func (*Data_Message) ProtoMessage()    {}

func (m *Data_Message) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *Data_Message) GetAccept() string {
	if m != nil && m.Accept != nil {
		return *m.Accept
	}
	return ""
}

func (m *Data_Message) GetSend() string {
	if m != nil && m.Send != nil {
		return *m.Send
	}
	return ""
}

func init() {
	proto.RegisterEnum("lm.Data_MessageType", Data_MessageType_name, Data_MessageType_value)
}
